import {
  gearHasTempEnchant,
  gearSetCount,
  getThreatCoefficient,
  handler_modDamage,
} from "../../era/base.js";

import * as era from "../../era/class/shaman.js";

export const config = {
  Mods: {
    ...era.config.Mods,
    MoltenBlast: 2.0,
    SpiritOfTheAlpha: 1.45,

    /**
     * While Rockbiter Weapon is active on your main hand weapon and you have a shield equipped,
     * you deal 65% increased threat
     */
    WayOfEarth: 1.65,

    LoyalBeta: 0.7,

    /** When Spirit of the Alpha is active, increases threat generated by 20%. */
    TAQ_Tank_4pc: 1.2,
  },
  Buff: {
    ...era.config.Buff,
    WayOfEarth: 408531,
    TranquilAirTotem: 25909,
    SpiritOfTheAlpha: 408696,
    LoyalBeta: 443320,
    TAQ_Tank_4pc: 1213937,
    ActivateWayOfEarth: 461635, // Utility buff to activate Way of Earth if conditions met
  },
  Spell: {
    ...era.config.Spell,
    EarthShockR1: 8042,
    EarthShockR2: 8044,
    EarthShockR3: 8045,
    EarthShockR4: 8046,
    EarthShockR5: 10412,
    EarthShockR6: 10413,
    EarthShockR7: 10414,
    EarthShockTaunt: 408690,

    MoltenBlast: 425339,
  },
  Tier: {
    ...era.config.Tier,
    TAQ_Tank: 1852,
  },
  Enchant: {
    SoulOfTheAlpha: 7683, // TAQ_Tank_4pc
    RockbiterWeapon: 7568,
  },
};

export const initialBuffs = {
  ...era.initialBuffs,
  [config.Buff.SpiritOfTheAlpha]: 0,
  [config.Buff.WayOfEarth]: 0,
  [config.Buff.TAQ_Tank_4pc]: 0,
};

export const buffNames = {
  ...era.buffNames,
  [config.Buff.TranquilAirTotem]: "Tranquil Air Totem",
  [config.Buff.SpiritOfTheAlpha]: "Spirit of the Alpha",
  [config.Buff.LoyalBeta]: "Loyal Beta",
  [config.Buff.WayOfEarth]: "Way of Earth",
  [config.Buff.TAQ_Tank_4pc]: "S03 - Item - TAQ - Shaman - Tank 4P Bonus",
  [config.Buff.ActivateWayOfEarth]: "Way of Earth (w/ Rockbiter + Shield)",
};

export const buffMultipliers = {
  ...era.buffMultipliers,
  [config.Buff.SpiritOfTheAlpha]: getThreatCoefficient(
    config.Mods.SpiritOfTheAlpha
  ),
  [config.Buff.LoyalBeta]: getThreatCoefficient(config.Mods.LoyalBeta),
  [config.Buff.TAQ_Tank_4pc]: {
    coeff: (buffs, spellId) => {
      if (config.Buff.SpiritOfTheAlpha in buffs) {
        return getThreatCoefficient(config.Mods.TAQ_Tank_4pc);
      }
      return getThreatCoefficient(1);
    },
  },
  [config.Buff.WayOfEarth]: {
    coeff: (buffs, spellId) => {
      if (config.Buff.ActivateWayOfEarth in buffs) {
        return getThreatCoefficient(config.Mods.WayOfEarth);
      }
      return getThreatCoefficient(1);
    },
  },
};

export const talents = {
  ...era.talents,
};

export const fixateBuffs = {
  ...era.fixateBuffs,
  [config.Spell.EarthShockTaunt]: true,
};

export const spellFunctions = {
  ...era.spellFunctions,
  // TODO: add taunt handler too
  [config.Spell.EarthShockTaunt]: handler_modDamage(config.Mods.EarthShock),

  [config.Spell.MoltenBlast]: handler_modDamage(config.Mods.MoltenBlast),
};

/**
 * @param {import("../../era/threat/wcl").WCLCombatantInfoEvent} unit
 * @param {Record<string, boolean>} buffs
 * @param {Record<string, number>} talents
 */
export const combatantImplications = (unit, buffs, talents) => {
  era.combatantImplications(unit, buffs, talents);

  if (
    gearSetCount(unit.gear, config.Tier.TAQ_Tank) >= 4 ||
    gearHasTempEnchant(unit.gear, config.Enchant.SoulOfTheAlpha)
  ) {
    buffs[config.Buff.TAQ_Tank_4pc] = true;
  }

  if (gearHasTempEnchant(unit.gear, config.Enchant.RockbiterWeapon)) {
    // TODO: shield detection
    buffs[config.Buff.ActivateWayOfEarth] = true;
  }
};

export const notableBuffs = {
  ...Object.values(config.Buff),
};

export const invulnerabilityBuffs = {};

export const auraImplications = {
  ...era.auraImplications,
  [config.Spell.MoltenBlast]: config.Buff.SpiritOfTheAlpha,
};
