name: Playwright Tests [manual]
on:
  issue_comment:
    types: [created]
  pull_request:
    branches: [master]

jobs:
  check-comment:
    runs-on: ubuntu-latest
    outputs:
      comment-id: ${{ steps.fc.outputs.comment-id }}
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "/test"
          # direction: last
          # nth: 0
      # - name: React to comment
      #   if: steps.fc.outputs.comment-id != 0
      #   uses: dkershner6/reaction-action@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commentId: ${{ steps.fc.outputs.comment-id }}
      #     reaction: "rocket"

  run-other-workflow:
    needs: [check-comment]
    uses: ./.github/workflows/playwright.yml
    if: ${{ needs.check-comment.outputs.comment-id != 0 }}
