name: Playwright Tests [manual]
on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    runs-on: ubuntu-latest
    outputs:
      comment-id: ${{ steps.fc.outputs.comment-id }}
    if: github.event.issue.pull_request
    steps:
      - name: Find Comment
        id: fc
        uses: peter-evans/find-comment@v2
        continue-on-error: true
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: "/test"
          direction: last
          nth: 0
      - name: Add reactions
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          reactions: rocket

  manual:
    needs: [check-comment]
    uses: ./.github/workflows/playwright.yml
    if: ${{ needs.check-comment.outputs.comment-id != 0 }}
